[DATABASE]
; UseDB is either TRUE|true|FALSE|false; is false otherwise
UseDB = true
; DBConn can be blank, if UseDB is FALSE. Should enclosed within quotes.
DBConn = "mysql:host=localhost"
DBName = localproxy

; DBType can be either mysql|oracle
DBType = mysql

DBusername = <username-here>
DBpasswd = <password-here>
MaxRecordCount = 10

[VIEW]
ShowProgress = false

[PROXY]
proxy = http://localhost/proxy/xhibit_proxy.php

[ERROR]
; DisplayError is either 0 (disabled) or 1 (enabled). Defaults to 0 in code.
DisplayError = 0
