[DATABASE]
; UseDB is either TRUE|true|FALSE|false; is false otherwise
UseDB = true
; DBConn can be blank, if UseDB is FALSE. Should enclosed within quotes.
DBConn = "mysql:host=localhost"
DBName = localproxy

; DBType can be either mysql|oracle
DBType = mysql

DBusername = <username-here>
DBpasswd = <password-here>
MaxRecordCount = 10

[VIEW]
ShowProgress = false

[XHIBIT]
location = /var/www/lan/xhibit/
url = http://192.168.1.254/page.php?login=true&ignoreBrowser=true&frameWidth=0&managerReloadMinutes=30&stylesheet=&uri=

[PROXY]
proxy = http://192.168.1.254/proxy/xhibit_proxy.php

[CDU]
cdu = http://192.168.1.254/cdu/index.php

[ERROR]
; DisplayError is either 0 (disabled) or 1 (enabled). Defaults to 0 in code.
DisplayError = 0